# main text of home
title: Stefan Arseneau
bio: Astronomer

# twitter summary info
description: space

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/pfp_square.png

# your site color theme, true for dark theme, 
# false to light theme, auto to switch with system.
dark-theme: false

url: https://stefanarseneau.github.io
# your url: https://USERNAME.github.io

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# if you don't have any of social below, comment the line
#facebook: myfacebook
#twitter: mytwitter
#instagram: myinstagram
#linkedin: mylinkedin
resume_social_links:
  resume_github_url:            "https://github.com/stefanarseneau"

exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "vendor",
  ]
