title: Stefan Arseneau
logo: /arseneausm.github.io/assets/stefan.jpg
description: Miller Department of Physics and Astronomy, Johns Hopkins University
theme: jekyll-theme-minimal
baseurl: /arseneausm.github.io
